### ISSUE TITLE
Adding a profile to an Entry corrupts the file

### ISSUE THREAD

**Issue by AbonShell** [giloushaker/nr-editor#2]
Steps to reproduce
1. Create a new shared selection entry
2. Create a profile type
3. try to create a profile on the new selection entry
4. entry disappears and corrupts the archive

Expected result:
1. entry should still be there with the new profile entry. 
[Warhammer 40,000 10th Edition.zip](https://github.com/giloushaker/nr-editor/files/11712418/Warhammer.40.000.10th.Edition.zip)

**Comment by giloushaker** [comment]
Fixed in 1.1.25

**Comment by AbonShell** [comment]
![profile be gone](https://github.com/giloushaker/nr-editor/assets/20672472/0b134cb0-593c-4c87-a6e4-5be90a7a1d07)
Still happening on 1.1.25

**Comment by giloushaker** [comment]
I see, seems to only happen when you have 'Type' selected as sorting order

**Comment by AbonShell** [comment]
bizarre

**Comment by giloushaker** [comment]
Should actually be fixed in 1.1.26
